name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install jupyter-book

      - name: Build Jupyter Book
        run: jupyter-book build mlb-book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: mlb-book/_build/html

